import test from "node:test";import assert from "node:assert/strict";
import {resolveEffectiveTradeSettings,evaluateUserProfitPlan} from "./tradeSettings.js";

const global={sizingMode:"PERCENT",percentBalance:2,defaultAmountUsd:100,maxAmountPerTradeUsd:500,maxTotalExposureUsd:2000,maxConcurrentPositions:5,maxSlippageBps:1200,takeProfitMode:"ADVANCED",tp1Pct:50,tp1SellPct:25,tp2Pct:100,tp2SellPct:25,tp3Pct:200,tp3SellPct:25,runnerPct:25,capitalRecoveryEnabled:false,trailingEnabled:false,sourceSellBehavior:"BRAIN_DECIDES",scalperCopyEnabled:false};

test("global plan wins when trader has no custom override",()=>{const s=resolveEffectiveTradeSettings(global,{useCustomSettings:false,fixedAmountUsd:999,takeProfitPct:999});assert.equal(s.sizingMode,"PERCENT");assert.equal(s.fixedAmountUsd,100);assert.equal(s.tp1Pct,50)});
test("per trader custom fields override global and scalper remains explicit",()=>{const s=resolveEffectiveTradeSettings(global,{useCustomSettings:true,sizingMode:"FIXED",fixedAmountUsd:75,tp1Pct:80,scalperCopyEnabled:true});assert.equal(s.sizingMode,"FIXED");assert.equal(s.fixedAmountUsd,75);assert.equal(s.tp1Pct,80);assert.equal(s.scalperCopyEnabled,true)});
test("advanced sells are percentages of original and protect runner",()=>{const s=resolveEffectiveTradeSettings(global,{useCustomSettings:false});const i=evaluateUserProfitPlan(s,{profitPct:60,drawdownFromPeakPct:0},{tp1Taken:false,tp2Taken:false,tp3Taken:false,principalRecoveredPct:0,peakProfitPct:60,remainingPct:100});assert.equal(i.action,"PARTIAL_TP");if(i.action==="PARTIAL_TP")assert.equal(i.sellPct,25)});
test("trailing protection can close the runner",()=>{const s=resolveEffectiveTradeSettings({...global,trailingEnabled:true,trailingActivationPct:80,trailingGivebackPct:20},{useCustomSettings:false});const i=evaluateUserProfitPlan(s,{profitPct:120,drawdownFromPeakPct:22},{tp1Taken:true,tp2Taken:true,tp3Taken:true,principalRecoveredPct:100,peakProfitPct:180,remainingPct:25});assert.equal(i.action,"EXIT")});
