import {db} from "@memecloud/db";
import {getConfig} from "@memecloud/config";
import {startHeartbeat} from "@memecloud/ops";
import {classifyPulse} from "@memecloud/social";
let scanned=0,updated=0,errors=0,running=false;
const positive=/\b(bull|bullish|send|sending|moon|ape|aped|gem|based|cook|cooking|breakout|runner|100x|10x|cto)\b/i;
const negative=/\b(rug|scam|dead|dump|dumping|sell|exit|honeypot|rekt)\b/i;
async function pulse(token:any,bearer:string){const now=new Date(),start=new Date(Date.now()-15*60_000);const q=[token.symbol?`$${token.symbol}`:null,token.mint,token.name?`\"${token.name}\"`:null].filter(Boolean).join(" OR ");const url=new URL("https://api.x.com/2/tweets/search/recent");url.searchParams.set("query",`(${q}) -is:retweet`);url.searchParams.set("start_time",start.toISOString());url.searchParams.set("max_results","100");url.searchParams.set("tweet.fields","created_at,author_id,public_metrics");const r=await fetch(url,{headers:{authorization:`Bearer ${bearer}`},signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error(`X_HTTP_${r.status}`);const b:any=await r.json(),rows:any[]=b.data??[];const t5=Date.now()-5*60_000,r5=rows.filter(x=>new Date(x.created_at).getTime()>=t5),authors=new Set(r5.map(x=>x.author_id)),p=rows.filter(x=>positive.test(x.text)).length,n=rows.filter(x=>negative.test(x.text)).length,sent=(p-n)/Math.max(1,p+n),velocity=r5.length/Math.max(1,(rows.length-r5.length)/2),spam=1-authors.size/Math.max(1,r5.length);const base={symbol:token.symbol||"",mint:token.mint,mentions5m:r5.length,mentions15m:rows.length,uniqueAuthors5m:authors.size,sentiment:sent,influencerMentions:0,spamRatio:Math.max(0,Math.min(1,spam)),velocity};return {...base,trend:classifyPulse(base)}}
async function tick(){if(running)return;running=true;try{const cfg=await getConfig<any>("social"),bearer=cfg?.xBearerToken||process.env.X_BEARER_TOKEN;if(!bearer)return;const tokens=await db.discoveryToken.findMany({where:{lastSeenAt:{gte:new Date(Date.now()-6*60*60_000)}},orderBy:{lastSeenAt:"desc"},take:40});for(const t of tokens){try{const p=await pulse(t,bearer);scanned++;const latest=await db.memeMarketSnapshot.findFirst({where:{chain:t.chain,mint:t.mint},orderBy:{observedAt:"desc"}});if(latest)await db.memeMarketSnapshot.update({where:{id:latest.id},data:{socialMentions5m:p.mentions5m,socialUniqueAuthors5m:p.uniqueAuthors5m,socialVelocity:p.velocity,socialSentiment:p.sentiment,socialSpamRatio:p.spamRatio,provenance:{...(latest.provenance as any||{}),x:{provider:"X_RECENT_SEARCH",observedAt:new Date().toISOString(),mentions15m:p.mentions15m,trend:p.trend}} as any}}).then(()=>updated++);}catch(e){errors++;console.error("[social-worker]",t.mint,e)}}}finally{running=false}}
startHeartbeat("social-hype",()=>({scanned,updated,errors,running,provider:"X_RECENT_SEARCH_WHEN_CONFIGURED"}));setInterval(()=>void tick(),15_000);void tick();console.log("[social-worker] online");
