"use client";
import {useState, type FormEvent} from "react";
import {Plus} from "lucide-react";
import {apiFetch,plainError} from "../../lib/api";

function TraderWalletControls({trader,admin,reload}:{trader:any;admin:boolean;reload:()=>void}){
 const[adding,setAdding]=useState(false),[chain,setChain]=useState("SOLANA"),[address,setAddress]=useState(""),[msg,setMsg]=useState("");
 async function add(){setMsg("");try{await apiFetch(`/v1/admin/traders/${trader.id}/wallets`,{method:"POST",body:JSON.stringify({chain,address,verified:true})});setAddress("");setAdding(false);reload()}catch(e){setMsg(plainError(e))}}
 async function remove(id:string){if(!confirm("Remove this public source wallet from the trader? Auto-copy monitoring for this mapping will stop."))return;setMsg("");try{await apiFetch(`/v1/admin/trader-wallets/${id}`,{method:"DELETE"});reload()}catch(e){setMsg(plainError(e))}}
 return <div className="trader-wallets-admin">
  {(trader.wallets||[]).length===0&&<small>No wallet mapped — tracking unavailable.</small>}
  {(trader.wallets||[]).map((w:any)=><div className="trader-wallet-chip" key={w.id}><span><b>{w.chain}</b><small>{String(w.address).slice(0,6)}…{String(w.address).slice(-5)} · {w.verified?"verified":"unverified"}</small></span>{admin&&<button title="Remove wallet" onClick={()=>remove(w.id)}>×</button>}</div>)}
  {admin&&!adding&&<button className="wallet-add-mini" onClick={()=>setAdding(true)}>+ Add source wallet</button>}
  {admin&&adding&&<div className="wallet-add-box"><select value={chain} onChange={e=>setChain(e.target.value)}><option>SOLANA</option><option>BASE</option><option>ETHEREUM</option><option>BNB</option><option>ARBITRUM</option><option>AVALANCHE</option></select><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Public wallet address"/><div><button disabled={!address.trim()} onClick={add}>Save</button><button onClick={()=>{setAdding(false);setAddress("");setMsg("")}}>Cancel</button></div>{chain!=="SOLANA"&&<small>Adapter-ready only: this wallet can be registered, but Auto Copy stays unavailable until that chain listener is implemented.</small>}</div>}
  {msg&&<small className="negative">{msg}</small>}
 </div>
}

export function TradersAdmin({d,reload,admin}:{d:any;reload:()=>void;admin:boolean}){const[open,setOpen]=useState(false);const[form,setForm]=useState<any>({displayName:"",handle:"",xHandle:"",category:"",wallet:"",chain:"SOLANA"});const[err,setErr]=useState("");
 async function add(e:FormEvent){e.preventDefault();setErr("");try{await apiFetch("/v1/admin/traders",{method:"POST",body:JSON.stringify({displayName:form.displayName,handle:form.handle,xHandle:form.xHandle,category:form.category,recommended:true,wallets:form.wallet?[{chain:form.chain,address:form.wallet,verified:true}]:[]})});setOpen(false);reload()}catch(e){setErr(plainError(e))}}
 async function patch(id:string,body:any){await apiFetch(`/v1/admin/traders/${id}`,{method:"PATCH",body:JSON.stringify(body)});reload()}
 return <>
  {admin&&<button className="action-primary" style={{padding:"10px 13px",borderRadius:12,marginBottom:12}} onClick={()=>setOpen(!open)}><Plus size={13}/> Add platform trader</button>}
  {open&&<section className="app-card" style={{marginBottom:10}}><form className="form-grid" onSubmit={add}><label className="field"><span>Name</span><input value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})} required/></label><label className="field"><span>Handle</span><input value={form.handle} onChange={e=>setForm({...form,handle:e.target.value})} required/></label><label className="field"><span>X handle</span><input value={form.xHandle} onChange={e=>setForm({...form,xHandle:e.target.value})}/></label><label className="field"><span>Category</span><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label className="field"><span>Chain</span><select value={form.chain} onChange={e=>setForm({...form,chain:e.target.value})}><option>SOLANA</option><option>BASE</option><option>ETHEREUM</option><option>BNB</option></select></label><label className="field"><span>Verified public wallet</span><input value={form.wallet} onChange={e=>setForm({...form,wallet:e.target.value})}/></label>{err&&<div className="auth-error span2">{err}</div>}<button className="action-primary span2" style={{height:42,borderRadius:12}}>Create trader</button></form></section>}
  <section className="app-card admin-table-wrap"><table className="admin-table trader-admin-table"><thead><tr><th>Trader</th><th>Source wallets</th><th>Followers</th><th>Signals</th><th>Featured</th><th>Recommended</th><th>Default</th><th>Enabled</th></tr></thead><tbody>{(d.traders||[]).map((t:any)=><tr key={t.id}><td><b>{t.displayName}</b><br/><small>@{t.handle}</small>{t.xHandle&&<><br/><small>X @{t.xHandle}</small></>}</td><td><TraderWalletControls trader={t} admin={admin} reload={reload}/></td><td>{t._count?.follows||0}</td><td>{t._count?.signals||0}</td><td><input type="checkbox" checked={t.featured} disabled={!admin} onChange={e=>patch(t.id,{featured:e.target.checked})}/></td><td><input type="checkbox" checked={t.recommended} disabled={!admin} onChange={e=>patch(t.id,{recommended:e.target.checked})}/></td><td><input type="checkbox" checked={t.defaultSelected} disabled={!admin} onChange={e=>patch(t.id,{defaultSelected:e.target.checked})}/></td><td><input type="checkbox" checked={t.enabled} disabled={!admin} onChange={e=>patch(t.id,{enabled:e.target.checked})}/></td></tr>)}</tbody></table></section>
 </>}
