"use client";
import {useEffect,useMemo,useState} from "react";import {ArrowUpRight,Radio,Users} from "lucide-react";import {apiFetch,money,pct} from "../lib/api";import {timeAgo} from "../lib/format";import {TokenAvatar} from "./TokenAvatar";
export default function DiscoverView({openToken,setView}:{brain:any[];brainDegraded:boolean;setView:(v:any)=>void;openToken:(s:{chain:string;mint:string})=>void}){
 const[events,setEvents]=useState<any[]>([]),[traders,setTraders]=useState<any[]>([]),[tab,setTab]=useState("buys");
 async function load(){const [f,t]=await Promise.all([apiFetch<any>("/v1/curated/flow"),apiFetch<any>("/v1/curated/traders")]);setEvents(f.events||[]);setTraders(t.traders||[])}
 useEffect(()=>{void load();const x=setInterval(()=>void load(),4000);return()=>clearInterval(x)},[]);
 const rows=useMemo(()=>events.filter(e=>tab==="all"||e.action==="BUY"),[events,tab]);
 return <><section className="app-card"><div className="card-title"><div><span>LIVE WALLET FEED</span><h2>What the tracked traders are buying</h2></div><span className="status-badge"><Radio size={11}/> LIVE</span></div><p style={{fontSize:12,color:"#8a8fa0"}}>Only real swaps from Admin-listed wallets appear here. Transfers and airdrops do not count.</p><div className="review-grid"><div><span>Buys today</span><b>{events.filter(e=>e.action==="BUY").length}</b></div><div><span>Tracked traders</span><b>{traders.length}</b></div></div></section>
 <div className="config-tabs"><button className={tab==="buys"?"active":""} onClick={()=>setTab("buys")}>New buys</button><button className={tab==="all"?"active":""} onClick={()=>setTab("all")}>Buys &amp; sells</button><button onClick={()=>setView("traders")}><Users size={13}/> Leaderboard</button></div>
 <div className="token-list hunt-list">{rows.map(e=><div className="token-row hunt-row" key={e.id} onClick={()=>openToken({chain:"SOLANA",mint:e.mint})}><TokenAvatar symbol={e.token?.symbol||e.token?.name}/><div className="token-row-main"><b>{e.token?.symbol||e.token?.name||"New token"}</b><small>{e.trader?.displayName} {e.action==="BUY"?"bought":"sold"} · {timeAgo(e.observedAt)}</small><small>{e.marketCapUsd?`${money(e.marketCapUsd)} MC`:"MC loading"}{e.amountUsd?` · ${money(e.amountUsd)} swap`:""}</small></div><div className="token-row-side"><span className={`status-badge ${e.action==="SELL"?"watch":""}`}>{e.action}</span><ArrowUpRight size={16}/></div></div>)}</div>
 {!rows.length&&<section className="app-card"><h3>No tracked-wallet swap yet</h3><p style={{fontSize:12,color:"#8a8fa0"}}>MemeCloud is connected to the Admin-curated wallets. A verified swap appears here as soon as it lands on-chain.</p></section>}
 <section className="app-card"><div className="card-title"><div><span>TOP TRADERS</span><h2>Observed performance</h2></div></div>{traders.slice().sort((a,b)=>(b.performance?.d30?.returnPct??-1e9)-(a.performance?.d30?.returnPct??-1e9)).slice(0,5).map(t=><div className="control-list" key={t.id}><div><span>{t.displayName}<small style={{display:"block"}}>@{t.handle} · {t.performance.d30.closed} measured closes</small></span><b>{pct(t.performance.d30.returnPct)}</b></div></div>)}</section></>;
}
